# Generated by Django 5.2.4 on 2025-07-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите email",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
