# Generated by Django 5.2.4 on 2025-08-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_price_lesson_price"),
        ("users", "0007_alter_payments_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="paid_lesson",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="materials.lesson",
                verbose_name="Отдельно оплаченный урок",
            ),
        ),
    ]
