# Generated by Django 5.2.4 on 2025-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сумма оплаты"
            ),
        ),
    ]
