# Generated by Django 5.2.4 on 2025-08-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Укажите стоимость курса",
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Укажите стоимость урока",
                null=True,
                verbose_name="Стоимость урока",
            ),
        ),
    ]
