# Generated by Django 5.2.4 on 2025-08-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_price_lesson_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите стоимость курса",
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
    ]
