# Generated by Django 5.2.4 on 2025-08-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Укажите стоимость курса", verbose_name="Стоимость курса"
            ),
        ),
    ]
