# Generated by Django 5.2.4 on 2025-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата и время обновления"
            ),
        ),
    ]
